spring:
  datasource:
    # Updated driver class for MySQL 9.x
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/keibav2
    username: ji-no
logging:
  level:
    org:
      springframework: WARN
#    com:
#      example:
#        demo:
#          repository: DEBUG
server:
  tomcat:
    accesslog:
      enabled: true
mybatis:
  # Boot 3 uses kebab-case property names
  config-location: classpath:/mybatis/mybatis-config.xml
